# Generated by Django 2.1.1 on 2018-11-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilerole',
            field=models.ForeignKey(default=4, on_delete='CASCADE', to='auth.Group'),
        ),
    ]
