# Generated by Django 2.1.1 on 2018-11-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20181130_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='studentList',
            field=models.TextField(blank=True, null=True),
        ),
    ]
