# Generated by Django 2.1.1 on 2018-11-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_attendance_studentlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rollnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
