# Generated by Django 2.2.7 on 2019-12-23 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_app', '0002_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_coaching', models.CharField(max_length=250, null=True)),
                ('Address_of_coaching', models.TextField(max_length=250)),
                ('mode', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=20)),
                ('from_class', models.CharField(max_length=50)),
                ('Communicating_facilities', models.CharField(max_length=250)),
                ('Available_streams_after_10th', models.CharField(max_length=250)),
                ('Type_of_board', models.CharField(max_length=50, null=True)),
                ('Total_Students', models.CharField(max_length=50)),
                ('safety_and_Securtiy_Measures', models.CharField(max_length=250)),
                ('CCTV', models.CharField(max_length=50)),
                ('students_per_teacher', models.CharField(max_length=50)),
                ('Mention', models.CharField(max_length=50)),
                ('Punishable_offence_include', models.CharField(max_length=100, null=True)),
                ('Total_teachers', models.CharField(max_length=50)),
                ('general_fee_structure', models.CharField(max_length=250)),
                ('sports_played', models.CharField(max_length=50)),
                ('Qualification_details_of_teachers', models.CharField(max_length=250)),
                ('Facilities_provided', models.CharField(max_length=250)),
                ('Major_achievements', models.CharField(max_length=150)),
                ('Glorious_alumni_network', models.CharField(max_length=150)),
                ('Teaching_ideology', models.CharField(max_length=150)),
                ('Future_plans_and_developments', models.CharField(max_length=50)),
                ('support_any_extra_activities_apart_from_curriculum', models.CharField(max_length=150)),
                ('Principal_message', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
